// Auth
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

// Home
export const SET_HOME_STATUS = 'SET_HOME_STATUS';
export const ADD_HOME_APPS = 'ADD_HOME_APPS';
export const RESET_HOME_APPS = 'RESET_HOME_APPS';
export const SET_HOME_CATEGORY = 'SET_HOME_CATEGORY';
export const SET_HOME_SORT_BY = 'SET_HOME_SORT_BY';
export const SET_HOME_SORT_ORDER = 'SET_HOME_SORT_ORDER';

// Dialogs
export const DIALOG_SUBMIT_APP_CLOSE = 'DIALOG_SUBMIT_APP_CLOSE';
export const DIALOG_SUBMIT_APP_OPEN = 'DIALOG_SUBMIT_APP_OPEN';
export const DIALOG_SUBMIT_APP_UPDATE = 'DIALOG_SUBMIT_APP_UPDATE';
